name: CI Pipeline - Automatizacion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compilar proyecto (Build Stage)
      run: mvn compile

    - name: Ejecutar pruebas automatizadas (Test Stage)
      run: mvn testgit add .github/workflows/maven.yml